title:              Fabian Schick
email:              schick.fab@gmail.com
description:        
author:             Fabian Schick
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://fabianschick.github.io"

# Social Profiles
github_username:    FabianSchick1  
linkedin_username: fabian-schick-692a4118a

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-latex
